In [2]:
import pandas as pd

import numpy as np

u =np.array([1,0])
v=np.array([0,1])
z=u+v

print(z)

[1 1]


In [28]:
u =np.array( [[1,2,3,4], [1,2,3,5],[1,2,3,4]] )
print(u)
print(u.size)
print(u.ndim)
print(u.shape)

print(u[2][1:4])

[[1 2 3 4]
 [1 2 3 5]
 [1 2 3 4]]
12
2
(3, 4)
[2 3 4]


In [30]:
a=np.array([0,1])

b=np.array([1,0])

z= np.dot(a,b)
print(z)

0


In [33]:



A=['1','2','3']

for a in A:

    print(2*a)



11
22
33


In [4]:
print(np.array([11,34]))

[11 34]
